version: "3"
services: 
  web:
    image: ghg-tool-app
    build: .
    command: npm start
    ports: 
      - "8081:8081"
    volumes:
      - /app
    links:
      - mongo
    depends_on: 
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
